---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Gin.
--- DateTime: 2024/1/16 9:25
---


--函数表
g_base = {}

g_base["采集"] = function()
    interact(doodad("名字:物资|止血草|河底的沙石|冰魂|浩气盟的物资|鱼篓|晶矿|马草|干柴|雪莲|铁血·犒赏|押运奖赏|物资堆", "距离<6", "距离最近"))

    if self().GetItemAmountInPackage(5, 4549) < 6 then
        interact(doodad("名字:曼陀罗", "距离<6", "距离最近"))
    end

    if self().GetItemAmountInPackage(5, 4550) < 6 then
        interact(doodad("名字:黄杜鹃", "距离<6", "距离最近"))
    end

    if self().GetItemAmountInPackage(5, 7925) < 20 then
        if self().GetItemAmountInPackage(5, 7923) < 20 then
            interact(doodad("名字:冰块", "距离<6", "距离最近"))
        end

        if self().GetItemAmountInPackage(5, 7924) < 20 then
            interact(doodad("名字:石灰粉", "距离<6", "距离最近"))
        end

        use(5, 7923)
    end

    if self().GetItemAmountInPackage(5, 7920) < 20 then
        interact(doodad("名字:发芽的土豆", "距离<6", "距离最近"))
    end

    if self().GetItemAmountInPackage(5, 7922) < 10 then
        interact(doodad("名字:发霉的饭菜", "距离<6", "距离最近"))
    end
end

g_base["酿酒打水"] = function()
    use(5, 35560)
    --if self().GetItemAmountInPackage(5, 35524) < 250 then
    --    use(5, 35560)
    --end
    --
    --if self().GetItemAmountInPackage(5, 35525) < 250 then
    --    use(5, 35560)
    --end
    --
    --if self().GetItemAmountInPackage(5, 35523) < 250 then
    --    use(5, 35560)
    --end
end

g_base["切换目标"] = function()
    g_base["20尺内敌人"] = npc("名字:重霄玄石矿|重霄玄石矿堆|洛丹|吐蕃劫匪|雨蝶|红眼黑蛇|白额蝎|毒狼蛛|雨蝶|金翅雨蝶", "自己距离<20", "可选中", "自己可视")
    if g_base["20尺内敌人"] ~= 0 then
        settar(g_base["20尺内敌人"])
    end
end

g_base["切换目标6"] = function()
    g_base["6尺内敌人"] = npc("名字:重霄玄石矿|重霄玄石矿堆|洛丹|吐蕃劫匪|雨蝶|红眼黑蛇|白额蝎|毒狼蛛|雨蝶|金翅雨蝶", "自己距离<6", "可选中", "自己可视")
    if g_base["6尺内敌人"] ~= 0 then
        settar(g_base["6尺内敌人"])
    end
end

g_base["杀猪"] = function()
    if fight() then

        return
    end

    if self().GetItemAmountInPackage(5, 7925) < 20 then
        if self().GetItemAmountInPackage(5, 7923) < 20 then
            interact(doodad("名字:冰块", "距离<6", "距离最近"))
        end

        if self().GetItemAmountInPackage(5, 7924) < 20 then
            interact(doodad("名字:石灰粉", "距离<6", "距离最近"))
        end

        use(5, 7923)
    end

    if self().GetItemAmountInPackage(5, 7920) < 20 then
        interact(doodad("名字:发芽的土豆", "距离<6", "距离最近"))
    end

    if self().GetItemAmountInPackage(5, 7922) < 10 then
        interact(doodad("名字:发霉的饭菜", "距离<6", "距离最近"))
    end
end

local castTable = {

}

castTable["剑出鸿蒙"] = function()
    cast(23969)
    cast(36099)
end

castTable["无方行尽"] = function()
    if tbuffstate("可锁足") and qidian() > 9 then
        cast(2674)
    end
end

castTable["万世不竭_二段"] = function()
    if qjcount() == 5 then
        cast(18654)
    end
end

castTable["凭虚御风"] = function()
    if buff("生太极") and dis() > 0 and dis() < 9 then
        cast("凭虚御风")
    end
end

castTable["三才化生"] = function()
    if dis() > 0 and dis() < 9 then
        cast("三才化生")
    end
end

castTable["八卦洞玄"] = function()
    if buff("会神") and qidian() > 9 and tbuffstate("可封内") then
        cast("八卦洞玄")
    end
end

g_base["气纯抓点"] = function()
    castTable["无方行尽"]()
    castTable["八卦洞玄"]()

    if tbuff("八卦洞玄") then
        if tbufftime("八卦洞玄") < 0.1 then
            castTable["万世不竭_二段"]()
            if qidian() > 7 then
                cast("两仪化形")
            end

            cast("九转归一")
            cast("太极无极")
        end

        if nobuff("紫气东来") and qidian() < 8 then
            cast("紫气东来")
        end

        if tbufftime("八卦洞玄") < 2.7 then
            castTable["剑出鸿蒙"]()
        end

        if tbufftime("八卦洞玄") < 2 then
            castTable["万世不竭_二段"]()
        end

        castTable["凭虚御风"]()
        castTable["三才化生"]()

        if qidian() > 8 then
            cast("两仪化形")
        else
            if nobuff("紫气东来") then
                cast("四象轮回")
            end
        end
    end

    if tnobuff("八卦洞玄") and tlife() < 0.3 then
        castTable["万世不竭_二段"]()
        if qidian() > 7 then
            cast("两仪化形")
        end
        cast("太极无极")
        cast("九转归一")
    end
end

g_base["kill"] = function()
    if qjcount() == 5 and bufftime("气剑") > 3 then

    end
end
local g_control = {
    killed = 100,
    max = 100;

    increment = function(self)
        self.killed = self.killed + 1
    end,

    start = function(self)
        self.killed = 0
    end,

    stop = function(self)
        self.killed = self.max
    end,

    running = function(self)
        self.killed = self.killed + 1
        return self.killed <= self.max
    end
}

g_base["指定心法"] = function(name)
    return xmountname(tid) == name
end

g_base["心法名称"] = function()
    return xmountname(tid)
end

g_base["瑞氛"] = function()
    if tbuffstate("可打断") and tbuffstate("可眩晕") then
        if cntime("剑飞惊天") == 0 and cntime("剑冲阴阳") == 0 then
            g_control["紫气东来"] = cn("紫气东来")
            if (tlife() > 0.9 and g_control["紫气东来"] > 2) or (tlife() < 0.8 and g_control["紫气东来"] > 1) or (tlife() < 0.6 and g_control["紫气东来"] > 0) then
                g_control:start()
            end
        end
    end

    if g_control:running() then
        cast("剑飞惊天")
        if (scdtime("剑飞惊天") == 0) then
            return
        end
        cast("剑冲阴阳")
        --cast(2690)
        if (scdtime("剑冲阴阳") == 0) then
            return
        end
        moveto(xpos(tid()))

        if cn("紫气东来") > 0 then
            cast("紫气东来")
        end

        if qidian() > 8 then
            cast("无我无剑")
        end

        if tlife() < 0.4 then
            cast("八荒归元")
        end
    end
end

g_base["浮香丘箱子"] = function(skillname)

    local id = doodad("名字:蓝方菌箱|红方菌箱", "距离<6", "距离最近")
    if id ~= 0 then
        if enemy("距离<20") ~= 0 then
            cast(skillname)
        end
        stopmove()
        if interact(id) then
            deltimer("浮香丘箱子")
        end
        exit()
    end

    id = doodad("名字:蓝方菌箱|红方菌箱", "距离<24", "距离最近")
    if id == 0 then
        return
    end

    local x, y, z = xpos(id);
    local tdis = pdis2(x, y)
    if enemy("距离<20") ~= 0 then
        cast(skillname)
    end
    if tdis > 14 then
        settimer("浮香丘箱子")
        if scdtime("蹑云逐月") > 0 then
            acast("迎风回浪", 180, { nX = x, nY = y })
        else
            acast("蹑云逐月", 0, { nX = x, nY = y })
        end
        return
    end

    if tdis > 6 then
        settimer("浮香丘箱子")
        if scdtime("凌霄揽胜") > 0 then
            acast("瑶台枕鹤", 90, { nX = x, nY = y })
        else
            acast("凌霄揽胜", -90, { nX = x, nY = y })

        end
        return
    end

    if tdis > 6 and gettimer("浮香丘箱子") < 1.5 then
        moveto(x, y, z)
    end
end