---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Gin.
--- DateTime: 2024/3/28 22:08
---

function findClosestCoordinateIndex(coordinate)

    local x, y, z = pos()
    local closestCoordinateIndex = cur
    local minDistance = math.huge

    local coordinates = coordinate
    local len = #coordinate
    for i = 1, len do
        local _x, _y, _z = coordinates[i][1], coordinates[i][2], coordinates[i][3]
        local distance = math.abs(x - _x) + math.abs(y - _y) + math.abs(z - _z)
        if minDistance > distance then
            minDistance = distance
            closestCoordinateIndex = i
        end
    end

    return closestCoordinateIndex
end

g_tools = {}
function autoMove(coordinate, reverse)
    initAutoMove(coordinate)
    print(g_tools.cur.."/".. g_tools.len)

    if g_tools.cur > g_tools.len or g_tools.cur < 1 then
        return true
    end

    if nobuff("ÆïÓù") then
        cast(53)
        return false
    end
    if next(coordinate) then
        if reverse then
            g_tools.cur = g_tools.cur - 1
        else
            g_tools.cur = g_tools.cur + 1
        end
    else
        moveto(coordinate[g_tools.cur][1], coordinate[g_tools.cur][2], coordinate[g_tools.cur][3])
    end

    return false
end

function resetAutoMove()
    g_tools.cur = nil
end

function next(coordinate)
    local x, y, z = pos()
    local _x, _y, _z = coordinate[g_tools.cur][1], coordinate[g_tools.cur][2], coordinate[g_tools.cur][3]

    if (math.abs(x - _x) < 100 and math.abs(y - _y) < 100 and math.abs(z - _z) < 500) then
        return true
    else
        return false
    end

end

function initAutoMove(coordinate)
    if g_tools.cur == nil then
        g_tools.cur = findClosestCoordinateIndex(coordinate)
    end

    g_tools.len = #coordinate
end

function startDelay()
    deltimer("delay")
    settimer("delay")
end

function getDelay()
    return gettimer("delay")
end

function delayed()
    return gettimer("delay") ~= 0
end