---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Gin.
--- DateTime: 2024/6/29 5:28
---

load("Macro/Lib_PVP.lua")
local f = {}
function Main()
    f["选中目标"]()
    g_func["释放技能"]("芙蓉并蒂")
    if tbuff("芙蓉并蒂") then
        g_func["释放技能"]("乱洒青荷")
    end

    if buff("乱洒青荷") and tnobuff("兰摧玉折") then
        g_func["释放技能"]("阳明指")
    end

    if tbuff("兰摧玉折|钟林毓秀") then
        g_func["释放技能"]("玉石俱焚")
    end
end

f["选中目标"] = function()
    if cdtime("芙蓉并蒂") == 0 then
        nid = player("可选中", "视线可达", "内功:太玄经", "自己可视", "可视自己", "关系:敌对", "距离<40", "角度<10")
        if notarget() or tid() ~= nid then
            settar(nid)
        end
    end
end
