---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Gin.
--- DateTime: 2024/7/7 3:44
---

function Main()
    if life() < 0.5 then
        cast("春泥护花")
        cast(132)
    end

    if mana() < 0.4 then
        cast("碧水滔天")
    end

    if notarget() then
        return
    end

    if fight() then
        cast("水月无间")
        cast("乱洒青荷")
    end


    cast("墨海临源")

    if buff("乱洒青荷") then
        cast("阳明指")
    end

    if tnobuff("兰摧玉折") then
        cast("兰摧玉折")
    end

    if tnobuff("钟林毓秀") and gettimer("钟林毓秀") > 2 then
        if cast("钟林毓秀") then
            settimer("钟林毓秀")
        end
    end


    if tnobuff("商阳指") then
        cast("商阳指")
    end

    if tbuff("商阳指") and tbuff("钟林毓秀") and tbuff("兰摧玉折") then
        cast("芙蓉并蒂")
        cast("玉石俱焚")
    end

    if tnobuff("快雪时晴") then
        cast("快雪时晴")
    end


    cast("阳明指")

end