---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Gin.
--- DateTime: 2024/7/7 14:03
---
load("Macro/Lib_E.lua")
load("Macro/Lib_Tools.lua")
local v = {}
v["高手如林"] = false
v["高手如林完成"] = false
v["毒医试药无穷尽"] = false
v["毒医试药无穷尽完成"] = false
v["铁匠炼剑缺冰魂"] = false
v["铁匠炼剑缺冰魂完成"] = false
v["笑看仁义乱敌营"] = false
v["笑看仁义乱敌营完成"] = false
v["逍遥自在收税金"] = false
v["逍遥自在收税金完成"] = false

v["任务完成"] = false

function Main()
    if map() ~= "龙门荒漠" then
        return
    end

    clickButton("Normal/OldQuestAcceptPanel/Btn_Sure/")

    if v["任务完成"] then
        return
    end

    if not hasGetTask() then
        moveToTaskNpc()
        getTask()
        return
    end

    if not v["毒医试药无穷尽完成"] and v["毒医试药无穷尽"] then
        v["毒医试药无穷尽进行"]()
    end

    if v["毒医试药无穷尽完成"] and not v["高手如林完成"] then
        v["高手如林进行"]()
    end

    if v["高手如林完成"] and not v["铁匠炼剑缺冰魂完成"] then
        v["铁匠炼剑缺冰魂进行"]()
    end

    if v["铁匠炼剑缺冰魂完成"] and not v["笑看仁义乱敌营完成"] then
        v["笑看仁义乱敌营进行"]()
    end

    if v["笑看仁义乱敌营完成"] and not v["逍遥自在收税金完成"] then
        v["逍遥自在收税金进行"]()
    end

end

function hasGetTask()
    return v["高手如林"] and v["毒医试药无穷尽"] and v["铁匠炼剑缺冰魂"] and v["笑看仁义乱敌营"] and v["逍遥自在收税金"]
end

function getTask()
    --你已接受了[高手如林！]。
    --你已接受了[战！毒医试药无穷尽]
    --已接受了[战！铁匠炼剑缺冰魂]。
    --你已接受了[战！笑看仁义乱敌营]。
    --你已接受了[战！逍遥自在收税金]。

    local taskNpc = npc("名字:何非笑", "距离<4")
    if taskNpc ~= 0 then
        if delayExecute("交互何非笑", 100) then
            interact(taskNpc)
        end

        dialog("高手如林！")
        dialog("战！毒医试药无穷尽")
        dialog("战！铁匠炼剑缺冰魂")
        dialog("战！笑看仁义乱敌营")
        dialog("战！逍遥自在收税金")
    end
end

function moveToTaskNpc()
    local taskNpc = npc("名字:何非笑", "距离<4")
    if taskNpc == 0 then
        autoMove(g_task_e["龙门荒漠_神行_攻防前置"], "龙门荒漠_神行_攻防前置", false)
    end
end

function delayExecute(name, count)
    if v[name .. "_计数"] == nil then
        v[name .. "_计数"] = 0
        return true
    end

    if v[name .. "_计数"] < count then
        v[name .. "_计数"] = v[name .. "_计数"] + 1
        return false
    else
        v[name .. "_计数"] = 0
        return true
    end
end


v["俘虏"] = 0
v["毒医试药无穷尽进行"] = function()
    print("毒医试药无穷尽进行")
    print(v["欲仙丸数量"]())
    if v["欲仙丸数量"]() == 4 then
        autoMove(g_task_e["龙门荒漠_攻防前置NPC_喂药"], "龙门荒漠_攻防前置NPC_喂药", false)
        local npcId = npc("名字:被虏的江湖人士", "距离<6")
        if npcId ~= 0 then
            v["俘虏"] = npcId;
            if delayExecute("喂药1", 50) then
                interact(npcId)
            end
            dialog("给俘虏服下[欲仙丸]")
        end
    end

    if v["欲仙丸数量"]() == 3 then
        local npcId = npc("名字:被虏的江湖人士", "距离<6", "ID不等于:".. v["俘虏"])
        if npcId ~= 0 then
            if delayExecute("喂药2", 50) then
                interact(npcId)
            end
            dialog("给俘虏服下[欲仙丸]")
        end
    end

    if v["欲仙丸数量"]() == 2 then
        autoMove(g_task_e["龙门荒漠_攻防前置NPC_喂药2"], "龙门荒漠_攻防前置NPC_喂药2", false)
        local npcId = npc("名字:被虏的江湖人士", "距离<6")
        if npcId ~= 0 then
            v["俘虏"] = npcId;
            if delayExecute("喂药3", 50) then
                interact(npcId)
            end
            dialog("给俘虏服下[欲仙丸]")
        end
    end

    if v["欲仙丸数量"]() == 1 then
        local npcId = npc("名字:被虏的江湖人士", "距离<6", "ID不等于:".. v["俘虏"])
        if npcId ~= 0 then
            if delayExecute("喂药4", 50) then
                interact(npcId)
            end
            dialog("给俘虏服下[欲仙丸]")
        end
    end

    if v["欲仙丸数量"]() == 0 then
        v["毒医试药无穷尽完成"] = true
    end

end

v["高手如林进行"] = function()
    autoMove(g_task_e["龙门荒漠_喂药2_孙永恒"], "龙门荒漠_喂药2_孙永恒", false)
    local did = doodad("名字:孙永恒的信物", "距离<40")
    if did ~= 0 then
        moveto(xpos(did))
        interact(did)
    end
    if v["孙永恒的信物"]() then
        v["高手如林完成"] = true
    end
end

v["铁匠炼剑缺冰魂进行"] = function()
    print("铁匠炼剑缺冰魂进行")

    if v["散落的冰魄数量"]() == 3 then
        v["铁匠炼剑缺冰魂完成"] = true
        return
    end

    if v["散落的冰魄数量"]() == 0 then
        autoMove(g_task_e["龙门荒漠_喂药2_冰魄"], "龙门荒漠_喂药2_冰魄", false)
    end

    local did = doodad("名字:散落的冰魂货箱", "距离<5")
    if did ~= 0 then
        --moveto(xpos(did))
        interact(did)
    end
end

v["笑看仁义乱敌营进行"] = function()
    if v["浩气盟的物资"]() == 3 then
        v["笑看仁义乱敌营完成"] = true
        return
    end

    local did = doodad("名字:浩气盟的物资", "距离<5")
    if did == 0 then
        autoMove(g_task_e["龙门荒漠_冰魄_浩气盟物资"], "龙门荒漠_冰魄_浩气盟物资", false)
    else
        interact(did)
    end
end
v["收租1"] = 0
v["收租2"] = 0
v["收租3"] = 0
v["收租4"] = 0
v["逍遥自在收税金进行"] = function()
    local nid = doodad("名字:休憩的商人", "距离<5")
    if nid == 0 then
        autoMove(g_task_e["龙门荒漠_冰魄_收租"], "龙门荒漠_冰魄_收租", false)
    end

    if v["收租1"] < 2 and delayExecute("收租1", 100) then
        interact(1073744300)
        v["收租1"] = v["收租1"] +1
    end

    if v["收租1"] > 1 and v["收租2"] < 2 and delayExecute("收租2", 100) then
        interact(1073744301)
        v["收租2"] = v["收租2"] +1
    end


    if v["收租2"] > 1 and v["收租3"] < 2 and delayExecute("收租3", 100) then
        interact(1073744302)
        v["收租3"] = v["收租3"] +1
    end

    if v["收租3"] > 1 and v["收租4"] < 2 and delayExecute("收租4", 100) then
        interact(1073744303)
        v["收租4"] = v["收租4"] +1
    end

    dialog("")
end
v["欲仙丸数量"] = function()
    return self().GetItemAmountInPackage(5, 30)
end

v["散落的冰魄数量"] = function()
    return self().GetItemAmountInPackage(5, 10872)
end

v["浩气盟的物资"] = function()
    return self().GetItemAmountInPackage(5, 10873)
end

v["孙永恒的信物"] = function()
    return self().GetItemAmountInPackage(5, 17385) == 1
end

function OnMessage(szMsg, szType)
    output(szMsg)
    if not v["高手如林"] and szMsg.find(szMsg, "高手如林") then
        output(1)
        v["高手如林"] = true
    end

    if not v["毒医试药无穷尽"] and szMsg.find(szMsg, "毒医试药无穷尽") then
        output(2)
        v["毒医试药无穷尽"] = true
    end

    if not v["铁匠炼剑缺冰魂"] and szMsg.find(szMsg, "铁匠炼剑缺冰魂") then
        output(3)
        v["铁匠炼剑缺冰魂"] = true
    end

    if not v["笑看仁义乱敌营"] and szMsg.find(szMsg, "笑看仁义乱敌营") then
        output(4)

        v["笑看仁义乱敌营"] = true
    end

    if not v["逍遥自在收税金"] and szMsg.find(szMsg, "逍遥自在收税金") then
        output(5)
        v["逍遥自在收税金"] = true
    end
end