---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Gin.
--- DateTime: 2024/2/2 0:49
---

local ok = false

function Main()
    local me = self()
    for i, v in pairs(me) do
        print(i,v)
    end
end