---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Gin.
--- DateTime: 2024/2/2 0:49
---

local counter = 0;

function Main()
    -- 0.5秒打印一次坐标点
    if counter % 8 == 0 then
        print(pos())
    end

    counter = counter + 1

end



