---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Gin.
--- DateTime: 2024/2/5 1:19
---

function Main()
    --interact(doodad("名字:物资|止血草|河底的沙石|冰魂|浩气盟的物资|鱼篓|晶矿|马草|干柴|雪莲|铁血·犒赏", "距离<6", "距离最近"))


    local nid = doodad("可拾取","距离最近")

    clickButton("Topmost/MB_DropItemSure/Wnd_All/Btn_Option1/")
    if nid ~= 0 then
        moveto(xpos(nid))
        interact(nid)
    end
end
