---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Gin.
--- DateTime: 2024/2/2 0:49
---
load("Macro/Lib_Base.lua")

--宏选项
addopt("打断", false)

--变量表
local v = {}
v["记录信息"] = true

--函数表
local f = {}

f["太虚剑意"] = "凭虚御风"
f["紫霞功"] = "凭虚御风"
f["山海心诀"] = "澄神醒梦"
f["离经易道"] = "星楼月影"


--主循环
function Main()
    if f.skillname == nil then
        f.skillname = f[xmountname(id())]
    end
    g_base["浮香丘箱子"](f.skillname)
end
