---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Gin.
--- DateTime: 2024/2/2 0:49
---
load("Macro/Lib_Base.lua")

--宏选项
addopt("打断", false)

--变量表
local v = {}
v["记录信息"] = true

--函数表
local f = {}

f["太虚剑意"] = "凭虚御风"
f["紫霞功"] = "凭虚御风"
f["山海心诀"] = "澄神醒梦"
f["离经易道"] = "星楼月影"
f["云裳心经"] = "鹊踏枝"
f["补天诀"] = "蛊虫献祭"


--主循环
function Main()
    if f.skillname == nil then
        f.skillname = f[xmountname(id())]
    end
    findBox(f.skillname)
end

function findBox(skillname)

    local nid = doodad("名字:蓝方菌箱|红方菌箱", "距离<6", "距离最近")
    if nid ~= 0 then
        if target() and tid() ~= id() then
            settar(id())
        end

        if enemy("距离<20") ~= 0 then
            cast(skillname)
        end
        stopmove()
        if interact(nid) then
            deltimer("浮香丘箱子")
        end
        exit()
    end

    nid = doodad("名字:蓝方菌箱|红方菌箱", "距离<24", "距离最近")
    if nid == 0 then
        return
    end

    local x, y, z = xpos(nid);
    local tdis = pdis2(x, y)
    if enemy("距离<20") ~= 0 then
        cast(skillname)
    end
    if tdis > 14 then
        settimer("浮香丘箱子")
        if scdtime("蹑云逐月") > 0 then
            acast("迎风回浪", 180, { nX = x, nY = y })
        else
            acast("蹑云逐月", 0, { nX = x, nY = y })
        end
        return
    end

    if tdis > 6 then
        settimer("浮香丘箱子")
        if scdtime("凌霄揽胜") > 0 then
            acast("瑶台枕鹤", 90, { nX = x, nY = y })
        else
            acast("凌霄揽胜", -90, { nX = x, nY = y })

        end
        return
    end

    if tdis > 6 and gettimer("浮香丘箱子") < 1.5 then
        moveto(x, y, z)
    end
end