---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Gin.
--- DateTime: 2024/5/13 1:38
---

local counter = 0

function Main(g_player)
    --cast("·¨±¦¡¤Óã²æ")
    --cast("·¨±¦¡¤ÓãÓ¥")
    --cast("·¨±¦¡¤ÓæÍø")
    --cast("·¨±¦¡¤Éñ»úÀ×")

    cast(35963)
    cast(35964)
    cast(35965)
    cast(35966)

    if counter == 16 then
        clickButton("Normal/GetFishPanel/WndContainer_ListAndOperation/WndContainer_NormalFishOperation/Btn_PutInBag/")
    end

    if counter > 16 then
        counter = 0
    else
        counter = counter + 1
    end
end

