---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Gin.
--- DateTime: 2024/5/13 1:38
---


function Main(g_player)
    --cast("法宝·鱼叉")
    --cast("法宝·鱼鹰")
    --cast("法宝·渔网")
    --cast("法宝·神机雷")

    cast(35963)
    cast(35964)
    cast(35965)
    cast(35966)

end

